services:
  db:
    image: postgres:17
    container_name: qflow_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qflow1234
      POSTGRES_DB: qflow_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: qflow_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://admin:qflow1234@db:5432/qflow_db
      JWT_SECRET: replace_this_with_a_long_random_string
      PORT: 3000
    depends_on:
      - db
    networks:
      - qflow

  frontend:
    build: ./frontend
    container_name: qflow_frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - qflow

volumes:
  pgdata:

networks:
  qflow:
    driver: bridge
