
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qflow1234
      POSTGRES_DB: qflow_db
    ports:
      - "5432:5432"
    volumes:

      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://admin:qflow1234@db:5432/qflow_db