services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qflow1234
      POSTGRES_DB: qflow_db
    ports:
      - "5432:5432"
    volumes:
      - ../SQL/init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ../SQL/data.sql:/docker-entrypoint-initdb.d/02_data.sql

  app:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://admin:qflow1234@db:5432/qflow_db
      JWT_SECRET: qflow_super_secret_key_2026
      GOOGLE_CLIENT_ID: 61511368401-9c86lcmevn2fb4rkl6ir3o292sqtnbh8.apps.googleusercontent.com